### PR TITLE
set target_cpu_variant

### PR DESCRIPTION
**Pull request by gabkol**
sir arco, I'm not sure if this change is good. But I always get a failure by building latest cwm touch with jenkins.

"bionic/libc/Android.mk:429: TARGET_CPU_VARIANT is not defined
bionic/libc/arch-arm/arm.mk:30: **\* "TARGET_CPU_VARIANT not set or set to an unknown value. Possible values are cortex-a5, cortex-a7, cortex-a8, cortex-a9, cortex-a15, krait, scorpion. Use generic for devices that do not have a CPU similar to any of the supported cpu variants.".  Stop.
build error!
Build failed."

But this change doesn't help. Do you know how to set it correctly? Am I in the right file?

Sorry for the attached graphics.c, ignor it. I have to learn github :D

### CODE REVIEW

**Comment by arco** [comment]
TARGET_CPU_VARIANT doesn't exist in CM-10.1, and I've already defined it in CM-10.2, so it must be something wrong at your end.

**Comment by gabkol** [comment]
Thanks Sir! But why does builder.clockworkmod.com give this build error? 
I tried building it with your files. There are only problems by building the touch version.

**Comment by arco** [comment]
Dunno, must be something wrong with how the touch version is built. Sounds like it's using CM-10.1 when building or something.

**Comment by gabkol** [comment]
It's very weird. I will try it again in a few days. Hope that it will work then. Anyway thanks for your help!

**Pull request closed without merging**
