### PR TITLE
Open source sensor libs

### PR DESCRIPTION
**Pull request by sirmordred**
Ok.. finally ı fixed all of compile errors and now lib is buildable from source
and also ı added libakm stuff for ak8975(magnet/orientation sensor)

akm part will handle both magnetic/orientatiton
ymahaBma222 will handle accelerometer
gp2a will handle proximity

ı didnt add light sensor because afaik ancora doesnt have right? or if ım wrong?

thats it

but unfortunatly due to lack of free time ı couldnt test it so hold on....f

### CODE REVIEW

**Comment by sirmordred** [comment]
@doadin you can also try this on ancora_tmo and give a feedback? :)

**Comment by doadin** [comment]
Sure i can probably get around to makeing a build within the next 2-3 days maybe. If so ill let you know how it turns out. The parts for the other sensors worked before so hopefully theres no problems with those. The akm part i see still has the call to the libafk now so that should make it work. Last build i had made long time ago had problems opening the sensor which the libakm handles...i guess time will tell :P ill try it as soon as i can. If it does work the next part is a app for calibration. the aresive devcon team aries parts app has this in it but well need to strip it down to just that...Anyways that off in the future. 

Also if anyone else sees this and tests i have details on the needed kernel parts here https://github.com/doadin/Ancora-Ancora_TMO-LibSensors .

**Comment by doadin** [comment]
Kernel Output:
input: sec_key as /devices/platform/msm_ssbi.0/pm8058-core/pm8xxx-keypad/input/input0
input: sec_touchscreen as /devices/virtual/input/input1
input: dock as /devices/virtual/input/input2
input: accelerometer as /devices/virtual/input/input3
input: proximity_sensor as /devices/virtual/input/input4
input: sec_power_key as /devices/virtual/input/input5

logcat trying to test acceleromiter:
/sys/class/input/vent3/device/enable enable sensor 0 operation not permited

Browsing with File Manager
/sys/class/input/input3/name = proximity_sensor
/sys/class/input/event3/name = proximity_sensor

Im a little confused on how the kernel registers it as 3 then the sysfs is made fliped?lol

Also testing magnetic which is the same as compass? logcat reads error activating sensor 1 (No such device)

**Comment by doadin** [comment]
I think i found why the compass wasnt able to change state gonna make some changes then ill report back. However if i do get it to enable its going to fail to work probably? because it depends on the bma accel?

**Comment by doadin** [comment]
ok scratch that i think the compass just isnt loading because it depends on the accel which is not enableing.

**Comment by doadin** [comment]
Also note the kernel message says input: accelerometer as /devices/virtual/input/input3
how ever opening /sys/devices/virtual/input/input3/name = proximity_sensor

sad we have gone in reverse sort of...at least before accel and proximity enabled. However i think the issue isnt necessarily with the driver code. I think things are just all fliped around since the sec_jack changed. And thats why accel is not working right now. I think if we can figure out what devices are getting/trying to get what sysfs address then make the apporpriate ramdisk change we would be set.

**Comment by doadin** [comment]
oh also not to mention isnt it odd that it says vent3 and not event3? >.<

**Comment by Harakhti** [comment]
@sirmordred from what I understood, the GP2A has two models, one with a light sensor and one without. Samsung seems to not have any idea which one is in the device either, and there's multiple different yes and no points everywhere, although it's safer to say no than wasting time. :stuck_out_tongue:

**Comment by doadin** [comment]
Well the ariesve set of kernel drivers has "defined(CONFIG_MACH_ANCORA_TMO) " in the gp2a driver and the proprietary sensor lib has light code in in so if your unsure just add the light sensor in the kernel see what happens. I dont know why they wouldnt enable it though if it was there...seems like it would be pretty pointless and a waste of their time/money. but hey who knows.

If you do test it make sure to grab the one from before they switched to opensource lib to ensure it working if possible.

**Comment by sirmordred** [comment]
@doadin @Harakhti  there is 2 variant of GP2A sensor. Type A have both proximity and light sensor and type B have only proximity sensor and ancora is using type B(and ariesve is using type A variant of GP2A sensor)

also @doadin apply the following changes:
revert sec_jack driver updates and then revert seck_jack related updates in ramdisk
and then replace/update all sensor drivers except ak8975(because ak8975 driver of akm company needs HAL updates which we dont have so we should use the same old ak8975 sensor driver in kernel)

@arco any help would be appreciated because we are so close to success

**Comment by Harakhti** [comment]
@sirmordred Right, the little bit wider second sensor bit and they originally share drivers...derp, we should just guess by visual appearance.

**Comment by doadin** [comment]
Yea i figured this a while ago but people keep mentioning it. lol

And ok i can give that a try i guess....might take me a min to figure it out lol ill make a new build tonight and report back.

**Comment by doadin** [comment]
Im actually not gonna be able to test for a bit if someone else want to. Sorry work got busy.

**Comment by sirmordred** [comment]
Ok ı compiled it but ım not able to test it at the moment so if anyone want to test it here is the file https://www.mediafire.com/?hkhl8442i43krca
Just replace with current sensors.ancora.so file in /system/lib/hw

**Comment by Harakhti** [comment]
@sirmordred I'll try under PA. Do you expect functionality or log error issues to look for?

**Comment by sirmordred** [comment]
thank you harakhti
yeah all sensors except compass should work(ı hope .D)
compass will likely not work because it will need calibration(so we probably need app like ariespart)

**Comment by sirmordred** [comment]
auhhh sorry... how did ı miss it... Forget it Harakhti...
it will also require kernel update otherwise all sensors won't work
ı will provide a kernel with updated sensor drivers soon

**Comment by Harakhti** [comment]
Alright :stuck_out_tongue: happens.

**Comment by doadin** [comment]
So ive been testing and it compiles now and proximity works and all the sensors are registered in the kernel. However in logcat im getting:

D/Sensors (  473): Bma222Sensor::~enable(0, 1)

D/Sensors (  473): Bma222Sensor::~enable(0, 1) open /sys/class/input/ԯ/device/enable

E/SensorService(  473): Error activating sensor 0 (Operation not permitted)

Idk what square is to know what to change permissions for...

input: sec_key as /devices/platform/msm_ssbi.0/pm8058-core/pm8xxx-keypad/input/input0
input: sec_touchscreen as /devices/virtual/input/input1
input: dock as /devices/virtual/input/input2
input: accelerometer as /devices/virtual/input/input3
input: proximity_sensor as /devices/virtual/input/input4
input: sec_power_key as /devices/virtual/input/input5
input: compass_sensor as /devices/virtual/input/input6

Is from kenrel

I have updated all the info here: https://github.com/doadin/Ancora-Ancora_TMO-LibSensors
note libsensors2 is the current most working version.

Edit ok so i have fixed that error and now it shows:
D/Sensors (  475): Bma222Sensor::~enable(0, 1)

D/Sensors (  475): Bma222Sensor::~enable(0, 1) open /sys/class/input/input3/enable

D/Sensors (  475): Bma222Sensor::~enable(0, 1) opened /sys/class/input/input3/enable

D/Sensors (  475): Bma222Sensor::~setDelay(0, 66667000)

D/Sensors (  475): Bma222Sensor::~setDelay(0, 66667000)

D/Sensors (  475): Bma222Sensor::~setDelay(0, 66667000)

D/Sensors (  475): Bma222Sensor::~setDelay(0, 66667000)

EDIT: So after more testing it appears its enableing and disableing the sensor and setting the delay but for some reason its still not working in sensor box app and it shows no data for xyz. Anyways repo is again up-to-date.

**Comment by sirmordred** [comment]
magnetic sensor(compass) and orientation sensors are working?
also in kernel side you should be using old ak8975 drivers but updated bma and gp2a drivers
also you are testing it on cm12 right?
then you should disable selinux shit
ı tought you already did what ı said

**Comment by doadin** [comment]
magnetic sensor(compass) and orientation sensors are not working it says device doesnt exists when it trying to enable. I think the sysfs config is mismatched somewhere. And i was using the new akm because thats whats in my copy of the repo which i had accepted your pull request for changes and thought it was up to date. And i was just about to change the bma to what the ADC team has which i believe is up to date? And i have been testing with selinux set to permisive. And yes im using update gp2a and its been working fine since the ADC team started.

**Comment by sirmordred** [comment]
hmm ı understood but we have to use old akm kernel drivers because of old libakmsensor
also can you send more logs for about mag and orient sensor?
we should look to logs to find something useful
then we can fix it
maybe sensors are crashing while dlopening the proprietary libakm.so
maybe something other
logs will tell us

**Comment by doadin** [comment]
I am about to make a new build and test will all the things in place that we just desicussed ill upload logs and stuff soon. So far though in logs it hasnt mention not being able to load libakm. All it says is something along the lines of unable to change state sensor 1 device doesnt exist. Ill report back soon...

**Comment by sirmordred** [comment]
ok doadin
also dont build whole rom for  testing libsensors
you can just build libsensor and kernel
make sensors.ancora instead of make -jx
this will reduce your test time

**Comment by doadin** [comment]
Yea i usually build whole rom but i dont clear the whole out dir because all the rom parts dont change and so it doesnt rebuild it anyways. And i did try "make bootimage" once but it seemed to take along time to even start is that how its supposed to be done?

**Comment by sirmordred** [comment]
just make clean
. build/envsetup.sh
lunch ancora....
make (libname) for example: make sensors.ancora

**Comment by sirmordred** [comment]
also doadin did you apply this? https://github.com/AriesVE-DevCon-TEAM/android_device_samsung_ariesve/commit/e2b47ccae38d1778499870d92f6d643c24595520

**Comment by doadin** [comment]
ok with the changes its now spaming:

D/AKMD2   (  475): 1064 hdata[0] = 

E/Sensors (  475): AkmSensor: unknown event (type=2, code=8)

E/Sensors (  475): AkmSensor: unknown event (type=2, code=6)

E/Sensors (  475): AkmSensor: unknown event (type=2, code=7)

E/Sensors (  475): AkmSensor: unknown event (type=2, code=9)

**Comment by doadin** [comment]
ok i think i see why its saying unknown event. Gonna build another test. 

i have EV_ABS instead of EV_REL.

**Comment by doadin** [comment]
ok i switched what the ADC team has for yass_acc and now touchscreen isnt working and its saying D/Sensors (  475): Bma222Sensor::~enable(0, 1)

D/Sensors (  475): Bma222Sensor::~enable(0, 1) open /sys/class/input//device/enable

E/SensorService(  475): Error activating sensor 0 (Operation not permitted)

**Comment by doadin** [comment]
Ok so using all stock kernel drivers except for proximity(gp2a) and using libsensors in its current form which is the same its been except i changed https://github.com/doadin/Ancora-Ancora_TMO-LibSensors/blob/master/libsensors/Bma222Sensor.cpp#L44

Was:
    if (data_fd) {
        strcpy(input_sysfs_path, "/sys/class/input/");
        strcat(input_sysfs_path, input_name);
        strcat(input_sysfs_path, "/device/");
        input_sysfs_path_len = strlen(input_sysfs_path);

```
    //enable(0, 1);
}
```

Now:
    if (data_fd) {
        strcpy(input_sysfs_path, "/sys/class/input/input3/");
        input_sysfs_path_len = strlen(input_sysfs_path);
        //enable(0, 1);
    }
}

I made this change because akm depends on accel and without this it would not work probably because of using still the stock bma222 kernel driver. With this change and using everything in the libsensor repo i have setup it yeilds:
Accelerometer Sensor(bma222): Not working. It enables/disables/sets delay all fine no data.
Orientation Sensor(akm): Does not work. Im assuming this is because it despends on accel which is giving ?bad/no? data and therefore breaks orientation.
Magnetic Sensor(akm): Works seems to enable/disable fine. Data seems to be reported same as with the proprietary code.(No adjustments Needed)
Proximity(GP2A): Works fine as it always has. Could maybe benefit from updates ADC team has made as of late.(Not makeing any changes for now since its working)

My latest attempts at using/porting the bma222 code from ADC team has yielded results of anything from breaking touchscrean working to gettting "<4>[  104.753417] [diony] bma_acc_work_func." spam with E/Sensors (  474): couldn't find 'accelerometer' input device

D/Sensors (  474): Bma222Sensor::Bma222Sensor()

D/Sensors (  474): Bma222Sensor::Bma222Sensor() open data_fd

Since bma seems fine using the current sysfs as is in kernel and userspace and in userspace it seems to continue (sets enable>sests delay) just fine im guessing somewhere in here: https://github.com/doadin/Ancora-Ancora_TMO-LibSensors/blob/master/libsensors/Bma222Sensor.cpp#L119

is where its failing and considering it DOES NOT say Bma222Sensor: unknown event im guessing the issue is somewhere in the if (type == EV_ABS) section.

**Comment by doadin** [comment]
Ok so what i have found is that by using the terminal "echo 1 > /sys/class/input/input3/enable" the device does enable and "echo 0 > /sys/class/input/input3/enable" It disables i have confirmed this by "cat /sys/class/input/input3/data" when enable is 1 i get 3 numbers all that change when the phone tilts. When enable is 0, all three numbers change and stay at 0. So the data is there its just not being read by the userspace for some reason.

I just noticed in logcat it says:
D/SensorService(  476): nuSensorService starting...
E/Sensors (  476): couldn't find 'accelerometer' input device
D/Sensors (  476): Bma222Sensor::Bma222Sensor()
D/Sensors (  476): Bma222Sensor::Bma222Sensor() open data_fd

Then later says:
D/Sensors (  476): Bma222Sensor::~enable(0, 1)
D/Sensors (  476): Bma222Sensor::~enable(0, 1) open /sys/class/input/input3/enable
D/Sensors (  476): Bma222Sensor::~enable(0, 1) opened /sys/class/input/input3/enable
D/Sensors (  476): Bma222Sensor::~hasPendingEvents 0
D/Sensors (  476): Bma222Sensor::~setDelay(0, 66667000)
D/Sensors (  476): Bma222Sensor::~setDelay(0, 66667000)

And i did confirm with the cat on sys/class/input/input3/data that it is enableing. And in the kernel: board-ancora_tmo: i have I2C_BOARD_INFO("accelerometer", 0x08)
bma_accel_driver: i have #define BMA_ACC_KERNEL_NAME      "accelerometer"
                              dev->name = "accelerometer";
                              .name = "accelerometer",
and if i cd /dev ls
it lists accelerometer
So...what does it mean it cant find accelerometer.....
The it cant find come from https://github.com/doadin/Ancora-Ancora_TMO-LibSensors/blob/master/libsensors/SensorBase.cpp#L126

In kernel:
<4>[  103.664550] [diony] bma_acc_set_enable = 1.
<4>[  103.681549] [HSS] [bma222_set_delay] delay = 10
<4>[  103.704132] [HSS] [bma222_set_delay] delay = 10
<4>[  103.706451] [HSS] [bma222_set_delay] delay = 10

So the userspace seems to be enableing and disableing and setting the delay like i thought.

So as it is our kernel bma kernel driver isnt registering a /event and i think thats why its not finding it and why the input_name from https://github.com/AriesVE-DevCon-TEAM/android_device_samsung_ariesve/blob/cm-12.0/libsensors/Bma222Sensor.cpp#L46 wasnt working.

By using the bma222 code as is from adc libsensors i get 
D/Sensors (  474): Bma222Sensor::~enable(0, 1)
D/Sensors (  474): Bma222Sensor::~enable(0, 1) open /sys/class/input//device/enable
E/SensorService(  474): Error activating sensor 0 (Operation not permitted)
While using the files 
yas.h yas_acc_driver-bma222.c yas_acc_kernel_driver.c and yas_cfg.h

like i said before the only thing i see in kernel logs is melfas_ts_work_func: i2c failed the rest looks normal:
<6>[    1.996490] input: sec_touchscreen as /devices/virtual/input/input1
<4>[    1.996765] [Touch] irq : 247, irq : 247
<6>[    1.996917] melfas_mcs8000_ts_probe: Start touchscreen sec_touchscreen 

echo 1/0 > /sys/class/input/input3/enable still enables and disables bma and cat /sys/class/input/input3/data still shows accel sensor data. So if we can figure out why the i2c is failing for  melfas and then change the permissions or the sysfs used to set the bma sensor enable/disable,delay. I think wed be set but i have no clue why its failing.

**Comment by doadin** [comment]
ok so i made the changes seen here:https://github.com/doadin/Ancora-Ancora_TMO-LibSensors/commit/012b20dfc32b483f9bdc3467dcaac8765e059ead

and it made accel work but with inverted xyz values(oppsosite values like "-2" instead of "2") but something in that change broke magnetic sensor. i think its because of the EV_ABS to EV_REL and/or the ABS_X etc to REL_X. However im really not sure. If anyone can test to confirm these and/or has any ideas that would be great lol. I have managed to get all but orientation work...just not all at the same time >.< .

Edit: So i reverted it back to EV_ABS and ABS_X ABS_Y ABS_Z, and magnetic was still broken. Ive made over 30 different builds now so i might not make any for a bit if anyone wants to try the one commit i mentioned above if you revert it you should be able to see how it flips too one set working and the other not. It also appears that akm is what the comment about needing /dev/accelerometer was referring to so maybe thats the change that broke it.

**Comment by doadin** [comment]
Ok so i made one last attempt because its soooo close and i got all of them working! The last thing to figure out is why accel is giving backwards/inverted/opposite values. As you can see here:https://github.com/doadin/Ancora-Ancora_TMO-LibSensors/blob/master/libsensors/Bma222Sensor.cpp#L144 this is how it handels it and since the kernel hasnt really changed im guessing its gotta be the convert_a values some how and considering they are just opposite we just have to invert them?

**Comment by doadin** [comment]
So for the accel i do "cat /sys/class/input/event3/device/data" and get 
cat /sys/class/input/event3/device/data
-1 -4 64
In the sensorbox app the "data" is shown as x: -0.1 y: -0.6 Z: 9.8.

Trying to keep the phone in the same exact possition on stock i get
cat /sys/class/input/input3/device/data
-1 -4 64
In the sensorbox app the "data" is shown as x: 0.1 y: 0.6 Z: 9.8.

So something must be wrong with the x and y convert in libsensor.

Edit: So i was thinking maybe if we change CONVER_X and CONVERT_Y to -1.0f/1000000.0f instead of 1.0f/1000000.0f that might work? That way it wiull invert them but keep Z the same since it doesnt seem to be wrong?

**Comment by doadin** [comment]
Ok so as i suspected makeing the change for CONVERT_X and CONVERT_Y it acts just like stock like it should. However it does seem that it at least for me isnt centered which we can just get or make or use adc teams app to calibrate it.

Or it was right and the surfce i have it on isnt flat or w.e. either way it all seems to work fine 100% like stock but faster so yay

**Comment by doadin** [comment]
I made all new pull requests to you @arco to make it easy. I know alot fo people use your repos and the pull requests should work 100% as is. The only thing i didnt test was changeing the accel_kernel_driver kernel_name back to accelerometer instead of YamahaBMA222. That way its one less change. And i dont see why it would make any difference but im sure your gonna test anyways and if it doesnt work just try changeing that and change the board-ancora to match.

Which also the ADC team is using a new bma222 driver that is different from the original which is why i was having a hard time figureing out why it wouldnt work like it did before. However in their new driver they too kept the kernel name as accelerometer so thats why im thinking it should be fine, also just because you could name it hippo if you wanted as long as you change it on board file too lol. The accelerometer_sensor is the part that really matters.

**Comment by sirmordred** [comment]
thank you very much for your works doadin ı was unable to compile/test this stuff for a long time(sorry for that) but it seems you succeded +1 :)
ım closing this now

**Comment by doadin** [comment]
yup and i have confirmed keeping the kernel name as accelerometer instead of yamahabma222 like i had it before does work so the only changes needed. Are updating the two kernel drivers bma_accel_driver.c and gp2a_proximity.c. And then make the device/vendor change. It could all use maybe some fixing up/clean up. But yea its opensource we can do what we want! It took me about 30 builds to get it right but now at least i can see accelerometer updates a lot more often than it did before so a bit performance boost there which should make things like games and gps that utilize it better.

And thank you for cleaning up the code esspecial the akm parts.

**Comment by doadin** [comment]
@sirmordred I actually think i have found a issue. Kind of. While all the sensors do work. When enabling a akm sensor logcat gets spamed with something like akmd2 hsdata. This is comeing from libakm.so. And im not sure if its because of all the spam or not but even after closeing the app that is using the sensor logcat still gets spamed as if its not closeing/disalbeing the sensor. Also i think it might be spaming so much it actually affect the performance of the phone.(untested but logcat even seemed to stutter a bit while it was happening could have been something else though)

**Comment by sirmordred** [comment]
ı think we can implement newer ak8975 driver with more proper way like blefish did https://github.com/Blefish/android_kernel_huawei_msm7x30/commit/b6dd361c47c1dd6d12a53755c8f91fdea87fd8c6
https://github.com/Blefish/android_kernel_huawei_msm7x30/commit/6f81bc340f1108f2347eed832f01c3e2fe3a49b3 but and then we can seperate bma accel driver and ak8975 magnetic driver ı think
and with this way we dont need old libakm library

**Comment by sirmordred** [comment]
sensor's gpio number on our boards is 180
ı think we can configure it out

**Comment by doadin** [comment]
Very rough first take on it:

https://github.com/doadin/android_device_samsung_ancora_tmo/commit/5d9e214b3dee9ca67c55f733eec488fefd492fe4

https://github.com/doadin/android_vendor_samsung_ancora_tmo/commit/e2528e4ef299a95f9cafac2c800a94c53e2b93b0

https://github.com/doadin/samsung-kernel-msm7x30/commit/d977b75b3567e252fa71ae032948d7b0bc3edc7f

The only things i changed different from what they have was changed "compass" to "compass_sensor" as i know in my testing accelerometer didnt work unless it was accelerometer_sensor for w.e. reason. We can figure that out later i guess. Obviously a lot of work is gonna be needed.

**Comment by doadin** [comment]
I have no idea what to do with the gpiomux stuff.

**Comment by doadin** [comment]
I think most of the changes should be pretty just straight up copy paste. The only thing that isnt and that i dont know how to deal with is the kernel/board-\* changes.

**Comment by doadin** [comment]
SO yea like i said the kernel changes are probablly all thats left, i just finished fixing up the device libsensor part so it should line up with the kernel driver change. Its up to you or arco now because im not that familiar with these kernel changes.

**Comment by sirmordred** [comment]
ı will try asap and ı wıll surely give you a feedback

**Comment by doadin** [comment]
i was looking the other night and it looks like we have a gpiomux file but its pretty much empty because none of our devices are setup to use it. So might be able to just add in the akm part to it. https://github.com/doadin/samsung-kernel-msm7x30/blob/cm-12.0-akm/arch/arm/mach-msm/gpiomux-7x30.c

**Comment by sirmordred** [comment]
gpiomux changes are just for suspend/resume feature
firstly we need to initialize chip itself through board

**Comment by doadin** [comment]
well i tried to matchup as much as i could from the links you provided if you see anything and/or can figure the rest out that would be great.

**Comment by doadin** [comment]
Idk what you have done so far if anything but i have made some kernel changes again today. Idk if they are useful or not but with these changes as far as i can tell we are 100% the same as the huawei msm7x30 kernel as far as i see so far. The only  change i see that i think needs changeing is the reg. Im not sure which regulator is used for akm on our device. Again hopefully this will at least help. This isnt really my area of expertise like i said but i dont want to leave the work 100% to you guys.

**Comment by sirmordred** [comment]
thank you for your works doadin ı couldnt look into new akm kernel driver stuff .Im working on bln implementation and vibrator strenght sysfs implementation right now but as ı promised ı will look into it and yes it needs reg initialization on board side then we need new akm hal and akmdfs binary but ı hope bma can work without proprietary libakm library

**Comment by doadin** [comment]
oh also the logcat spam was more due to an improper use of sensor by a specific app. However i think we could still benifit from using the opensource version. Like i also said before i already made the device side change and only the kernel changes should be left. Do you know could you tell me which reg is used for our akm on our board? If you could i could probably test this more myself.

**Pull request closed without merging**
