### PR TITLE
[Do Not Merge Yet] CameraHAL Updates

### PR DESCRIPTION
**Pull request by sirmordred**
ı have made some changes and
the only thing which is not working is video recording at the moment(everything else is working good)
and seems camera preview(especially on photo mode) is no more laggy with these changes  :)
ım trying to fix video problem ATM
probably ı deleted some important codes mistakenly

can you review this patchset sir?

thanx
regards

### CODE REVIEW

**Comment by arco** [comment]
Frame rate needs to be 30 for video recording to work.

**Comment by sirmordred** [comment]
hmm thank you very much for your hint sir
ı got this change originally from CAF https://www.codeaurora.org/cgit/quic/la/platform/hardware/qcom/camera/commit/?h=ics_chocolate&id=e307716e69450c9a76952d80036bbe35e3dea667
ı was thinking it can be work on our HAL but it couldnt

ok everything else except fps commit should be ready to go... :)

thanx again
regards

**Comment by sirmordred** [comment]
ok sir ı will rebase cameraHAL changes into single commit so easy-cherry-picking .D

**Comment by Madridii** [comment]
So buggy IMG (not focused totally) fixed?

**Comment by CastagnaIT** [comment]
> hmm thank you very much for your hint sir
> ı got this change originally from CAF https://www.codeaurora.org/cgit/quic/la/platform/hardware/qcom/camera/commit/?h=ics_chocolate&id=e307716e69450c9a76952d80036bbe35e3dea667
> ı was thinking it can be work on our HAL but it couldnt

You can not see changes in caf, our camera driver is a closed project samsung
since can not be update the camera drivers is useless to continue to change the hal
you will not get any improvement...

**Pull request closed without merging**
