### PR TITLE
Update lights.c

### PR DESCRIPTION
**Pull request by blackrow67**
BLN Support ancora

### CODE REVIEW

**Comment by arco** [comment]
Hmm, we don't have these devices, so I don't think this will work.

**Comment by blackrow67** [comment]
bln stock rom working arco

**Comment by arco** [comment]
Admittedly, it's been a while since I used stock rom, but I don't remember such an option. It there is, please show me a screenshot of it.

**Comment by blackrow67** [comment]
arco stock rom LED is lit when it comes to message

**Comment by arco** [comment]
That's not BLN. In gingerbread the behavior was like that - screen turned
on when message was received,  but Google changed it in ICS to not turn on.
Why I don't know, and I'm not bothered by it.

**Comment by blackrow67** [comment]
hmm arco too bad the sound of music on the device, can you fix it

**Pull request closed without merging**
