### PR TITLE
Some fixes & updates

### PR DESCRIPTION
**Pull request by sirmordred**

### CODE REVIEW

**Comment by sirmordred** [comment]
@arco  can you review this patchset sir? thanx regards

**Comment by sirmordred** [comment]
Ok except the two following commit https://github.com/sirmordred/android_device_samsung_ancora/commit/6dbd3401bab3c7084a8327aa5e2b03864628b175 https://github.com/sirmordred/android_device_samsung_ancora/commit/ecfeab97fab7edbf71916b26b72bfd946568390c this should be good
Also ı didnt test the following commit yet https://github.com/sirmordred/android_device_samsung_ancora/commit/6d8fff7fbbd26d41272b0832f6aeafc4cc69c349

**Comment by sirmordred** [comment]
any review?

**Comment by arco** [comment]
No time yet. Busy with the serrano.

**Comment by sirmordred** [comment]
ok ı will provide new cleaner patch

**Pull request closed without merging**
