### PR TITLE
Included building of the kernel into CM's build process

### PR DESCRIPTION
**Pull request by ralisi**
adding includes in include/ due to undefined macros

### CODE REVIEW

**Comment by hey-o** [comment]
Are you sure that the copy of the defconfig is needed here?
Also, in my opinion for TARGET_KERNEL_SOURCE, something like msm7x30-common would be better.

**Comment by ralisi** [comment]
czobor, I tested it, seems that the copy of defconfig is not necessary, so I removed it.
About the path to the kernel source, I have no idea what the conventions on that are.

**Comment by mikeNG** [comment]
in sony ericsson devices we use TARGET_KERNEL_SOURCE := kernel/semc/msm7x30
most cm devices use "kernel/<vendor>/<arch>" naming too

**Comment by hey-o** [comment]
yes, sorry I mean kernel/samsung/msm7x30-common

**Pull request closed without merging**
