### PR TITLE
Comment out G wireless line

### PR DESCRIPTION
**Pull request by iattilagy**
Hi arco,
Is there any reason to use this line? It limits us to g firmware while our hardware is capable of n. It seem to work this way, at least no drawback, but I can't detect if it is connected with n, the only thing that show difference is a network signal app: 72Mbps instead 54Mbps.

### CODE REVIEW

**Comment by arco** [comment]
There's probably a reason, as I see most other devices are also using it. I'll test without it and see what happens.

**Comment by doadin** [comment]
I dont know if it makes a difference or not but WITH this line i get 72Mbps. Which is the max for bcm4329?

**Comment by arco** [comment]
I'm getting 65 Mbps with and without this, so no change for me. My wireless router is also N cabable.

**Comment by doadin** [comment]
Yea. It seems like its using n but i guess if anything we could add n to the line. However since its already using it i don't think it will matter. Just like removing or keeping the line doesn't change anything.

**Comment by arco** [comment]
I think we'll just keep it as it is.

**Pull request closed without merging**
