### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by sirmordred**
it should be ready to go ;)

### CODE REVIEW

**Comment by Christopher83** [comment]
Hi,
to avoid this mess of already applied commits, you should rebase the branch to pull...

 git remote add arco https://github.com/arco/android_device_samsung_ancora.git 
 git fetch arco
 git checkout -b updates
 git rebase arco/cm-12.0

If there're conflicts, you should solve them, after that push the new branch on your GitHub and create a new clean pull.
The same could be made on vendor repo side.

Take a look at the documentation of the basic commands of Git, they could be surely useful for you in the future...

**Comment by sirmordred** [comment]
ok ı cleaned up the mess
thanx for the tip @Christopher83

**Comment by sirmordred** [comment]
patch bomb :)

Any review sir?
are you still busy with your serrano?
regards

**Comment by arco** [comment]
Yeah, busy with many things. Will try to get to it soon.

**Comment by sirmordred** [comment]
any review @arco ?
ı tested all patches in this pull request (f2fs-twrp branch) and everything is good

**Comment by rtammekivi** [comment]
What issue do you have with 720p?

**Comment by Madridii** [comment]
Hello @Blefish ..
When recording with 720p the camera app will close after some seconds (Maybe a crash) immediately

**Comment by arco** [comment]
I'm having the damn flu at the moment, but I have most of these merged locally. Just not sure when I'll get around pushing it upstream.

**Comment by sirmordred** [comment]
get well soon arco ;)

**Comment by sirmordred** [comment]
ok ım waiting now.. no more patch from me.. the whole patchset is enough for new build ı think.. its time for new build..

**Comment by sirmordred** [comment]
rebased the pull request

**Comment by arco** [comment]
If there's anything else that should be merged, push again cleanly without all the old stuff, and only if it's tested AND working.

**Pull request closed without merging**
